resource_group_name     = "rg-terraform-web-sql-db"
resource_group_location = "westeurope"
app_service_plan_name   = "appserviceplan-web-alakh"
app_service_name        = "terraform-web-alakh"
sql_server_name         = "terraform-sqlserver-alakh"
sql_database_name       = "ProductsDB"
sql_admin_login         = "admin"
sql_admin_password      = "admin1234567890!@"